### ISSUE TITLE
Add ability to fill form input values (for the jQuery plugin)

### ISSUE THREAD

**Issue by jtsternberg** [petenelson/bacon-ipsum#3]
Currently, this only appends text. Would be awesome if you could specify to set the `.val()` of the element.

**Comment by jtsternberg** [comment]
Since I don't see a place to submit a PR for the jquery plugin, https://gist.github.com/jtsternberg/ae82fc2db2e70c03b2b3a049c3d8480e

**Comment by petenelson** [comment]
I'll get this added as a repo so you can submit a PR.

**Comment by petenelson** [comment]
Here's the repo https://github.com/petenelson/jquery-bacon-ipsum.  I reformatted the code a little bit, but you should be able to make your changes in a PR.  Thanks!
